
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [1]:
import numpy as np

array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [2]:
array = np.arange(1,10)
reshaped_array = array.reshape((3,3))
reshaped_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Access the element at the second row, second column.


In [3]:
reshaped_array[1][1]

5

Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [9]:
array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])

addition = array_1 + array_2

subtraction = array_2 - array_1

multiplication = array_1 * array_2

division = array_1 / array_2


# addition
# subtraction
# multiplication
division

array([0.25, 0.4 , 0.5 ])

Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [14]:
array = np.array([1,2,3,4,5])

array_sum = array.sum()

array_mean = array.mean()

array_std = array.std()

print("Sum:", array_sum, "Mean:", array_mean, "Standard Deviation:", array_std)

Sum: 15 Mean: 3.0 Standard Deviation: 1.4142135623730951


Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [17]:
array_3 = np.array([1,2,3,4,5,6])

reshaped_array_3 = array_3.reshape((2,3))

reshaped_array_3

array([[1, 2, 3],
       [4, 5, 6]])


# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [30]:
random_array = np.random.randint(1,100,size = (5,5))

random_array

array([[17, 76, 17, 34,  4],
       [61, 69, 71, 30,  2],
       [30, 61, 58, 96, 41],
       [34, 96, 37,  4, 66],
       [75, 26, 69, 58, 29]])

Replace all values in the sub-array with a specific value.


In [31]:
random_array[3:5,1:3] = 10
random_array

array([[17, 76, 17, 34,  4],
       [61, 69, 71, 30,  2],
       [30, 61, 58, 96, 41],
       [34, 10, 10,  4, 66],
       [75, 10, 10, 58, 29]])

Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [42]:
array_4 = np.array([[1, 2],
           [3, 4],
           [5, 6],
           [7, 8]])

array_4[[1,3]]

array([[3, 4],
       [7, 8]])


# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [44]:
# Method 1
random_float = np.random.randint(0,2, size = (3,3))
random_float

array([[1, 1, 0],
       [0, 1, 1],
       [1, 0, 0]])

In [49]:
# Method 2
array_5 = np.array([0,1,2])
new_array = np.tile(array_5, (3,1))   # np.tile(array, (rows_repeatition of array, column_repeatition of array))
new_array

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [52]:
array_6 = np.array([6,7,8])

new_array + array_6


array([[ 6,  8, 10],
       [ 6,  8, 10],
       [ 6,  8, 10]])

# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [57]:
# 1.
random_array_2 = np.random.randint(1,19,size=(3,3))
random_array_3 = np.random.randint(2,25,size = (3,3))
print(random_array_2)
print(random_array_3)

[[15  3  2]
 [ 5  4 15]
 [11  3  3]]
[[14 11 15]
 [24  3  9]
 [10 23  9]]


In [63]:
# 2. hstack
concatenated_horizontally = np.hstack((random_array_2,random_array_3))
concatenated_horizontally

array([[15,  3,  2, 14, 11, 15],
       [ 5,  4, 15, 24,  3,  9],
       [11,  3,  3, 10, 23,  9]])

In [62]:
# 2. vstack

concatenated_vertically = np.vstack((random_array_2, random_array_3))
concatenated_vertically

array([[15,  3,  2],
       [ 5,  4, 15],
       [11,  3,  3],
       [14, 11, 15],
       [24,  3,  9],
       [10, 23,  9]])

In [74]:
# 3. Splitting concatenated arrays

split_horizontally = np.hsplit(concatenated_horizontally,2)
# split_horizontally[0][1]
split_vertically

[array([[15,  3,  2],
        [ 5,  4, 15],
        [11,  3,  3]]),
 array([[14, 11, 15],
        [24,  3,  9],
        [10, 23,  9]])]

In [75]:
# 3. 

split_vertically = np.vsplit(concatenated_vertically,2)
# split_vertically[0]
split_vertically

[array([[15,  3,  2],
        [ 5,  4, 15],
        [11,  3,  3]]),
 array([[14, 11, 15],
        [24,  3,  9],
        [10, 23,  9]])]

# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

In [82]:
nums = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]
repeatition = 0
repeated_num = 0

for i in range(len(nums)):
    if nums.count(nums[i]) > repeatition:
        repeatition = nums.count(nums[i])
        repeated_num = nums[i]


print(repeated_num)

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (4285554586.py, line 10)

# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

